@url= http://localhost:3727

### GET BASE
{{url}}

### GET person
GET {{url}}/person

### GET projects
GET {{url}}/projects


### GET skills
GET {{url}}/skills


### GET DATA
GET {{url}}/contacts


### POST DATA
POST {{url}}/contact
Content-Type: application/json

{

"name": "Abdul",
"subject":"backend",
"message":"Hallo wie gehts?",
"email":"hamdon@gmail.com"

}

