@url= http://localhost:3627

### GET BASE
{{url}}

### GET DATA
GET {{url}}/contacts


### POST DATA
POST {{url}}/contact
Content-Type: application/json

{

"name": "Abdul",
"subject":"backend",
"message":"Hallo wie gehts?",
"email":"hamdon@gmail.com"

}

